package sort

import "ProjectGoLive/pkg/models"

// test data
var list1 = []*models.Product{
	{
		ProductID: 1,
		Name:      "Product 1",
		Desc:      "This is Product 1.",
		Price:     1.00,
		Inventory: 100,
		Rating:    3.0,
		RatingNum: 80,
		UnitSold:  100,
	},
	{
		ProductID: 2,
		Name:      "Product 2",
		Desc:      "This is Product 2. ",
		Price:     1.00,
		Inventory: 100,
		Rating:    3.0,
		RatingNum: 80,
		UnitSold:  90,
	},
	{
		ProductID: 3,
		Name:      "Product 3",
		Desc:      "This is Product 3.",
		Price:     1.00,
		Inventory: 100,
		Rating:    2.5,
		RatingNum: 80,
		UnitSold:  90,
	},
	{
		ProductID: 4,
		Name:      "Product 4",
		Desc:      "This is Product 4.",
		Price:     1.00,
		Inventory: 100,
		Rating:    2.5,
		RatingNum: 60,
		UnitSold:  90,
	},
	{
		ProductID: 5,
		Name:      "Product 5",
		Desc:      "This is Product 5.",
		Price:     1.00,
		Inventory: 80,
		Rating:    2.5,
		RatingNum: 60,
		UnitSold:  90,
	},
	{
		ProductID: 6,
		Name:      "Product 6",
		Desc:      "This is Product 6.",
		Price:     2.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 7,
		Name:      "Product 7",
		Desc:      "This is Product 7.",
		Price:     2.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 8,
		Name:      "Product 8",
		Desc:      "This is Product 8.",
		Price:     2.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 9,
		Name:      "Product 9",
		Desc:      "This is Product 9.",
		Price:     2.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 10,
		Name:      "Product 10",
		Desc:      "This is Product 10.",
		Price:     3.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 11,
		Name:      "Product 11",
		Desc:      "This is Product 11.",
		Price:     3.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 12,
		Name:      "Product 12",
		Desc:      "This is Product 12.",
		Price:     3.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 13,
		Name:      "Product 13",
		Desc:      "This is Product 13.",
		Price:     3.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 14,
		Name:      "Product 14",
		Desc:      "This is Product 14.",
		Price:     4.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 15,
		Name:      "Product 15",
		Desc:      "This is Product 15.",
		Price:     4.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 16,
		Name:      "Product 16",
		Desc:      "This is Product 16.",
		Price:     4.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 17,
		Name:      "Product 17",
		Desc:      "This is Product 17.",
		Price:     4.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 18,
		Name:      "Product 18",
		Desc:      "This is Product 18.",
		Price:     5.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 19,
		Name:      "Product 19",
		Desc:      "This is Product 19.",
		Price:     5.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 20,
		Name:      "Product 20",
		Desc:      "This is Product 20.",
		Price:     5.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 21,
		Name:      "Product 21",
		Desc:      "This is Product 21.",
		Price:     5.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 22,
		Name:      "Product 22",
		Desc:      "This is Product 22.",
		Price:     6.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 23,
		Name:      "Product 23",
		Desc:      "This is Product 23.",
		Price:     6.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 24,
		Name:      "Product 24",
		Desc:      "This is Product 24.",
		Price:     6.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 25,
		Name:      "Product 25",
		Desc:      "This is Product 25.",
		Price:     6.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 26,
		Name:      "Product 26",
		Desc:      "This is Product 26.",
		Price:     7.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 27,
		Name:      "Product 27",
		Desc:      "This is Product 27.",
		Price:     7.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 28,
		Name:      "Product 28",
		Desc:      "This is Product 28.",
		Price:     7.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 29,
		Name:      "Product 29",
		Desc:      "This is Product 29.",
		Price:     7.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 30,
		Name:      "Product 30",
		Desc:      "This is Product 30.",
		Price:     8.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 31,
		Name:      "Product 31",
		Desc:      "This is Product 31.",
		Price:     8.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 32,
		Name:      "Product 32",
		Desc:      "This is Product 32.",
		Price:     8.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
}

var list2 = []*models.Product{
	{
		ProductID: 1,
		Name:      "Product 1",
		Desc:      "This is Product 1.",
		Price:     1.00,
		Inventory: 100,
		Rating:    3.0,
		RatingNum: 80,
		UnitSold:  100,
	},
	{
		ProductID: 2,
		Name:      "Product 2",
		Desc:      "This is Product 2. ",
		Price:     1.00,
		Inventory: 100,
		Rating:    3.0,
		RatingNum: 80,
		UnitSold:  90,
	},
	{
		ProductID: 3,
		Name:      "Product 3",
		Desc:      "This is Product 3.",
		Price:     1.00,
		Inventory: 100,
		Rating:    2.5,
		RatingNum: 80,
		UnitSold:  90,
	},
	{
		ProductID: 4,
		Name:      "Product 4",
		Desc:      "This is Product 4.",
		Price:     1.00,
		Inventory: 100,
		Rating:    2.5,
		RatingNum: 60,
		UnitSold:  90,
	},
	{
		ProductID: 5,
		Name:      "Product 5",
		Desc:      "This is Product 5.",
		Price:     1.00,
		Inventory: 80,
		Rating:    2.5,
		RatingNum: 60,
		UnitSold:  90,
	},
	{
		ProductID: 6,
		Name:      "Product 6",
		Desc:      "This is Product 6.",
		Price:     2.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 7,
		Name:      "Product 7",
		Desc:      "This is Product 7.",
		Price:     2.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 8,
		Name:      "Product 8",
		Desc:      "This is Product 8.",
		Price:     2.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 9,
		Name:      "Product 9",
		Desc:      "This is Product 9.",
		Price:     2.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 10,
		Name:      "Product 10",
		Desc:      "This is Product 10.",
		Price:     3.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 11,
		Name:      "Product 11",
		Desc:      "This is Product 11.",
		Price:     3.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 12,
		Name:      "Product 12",
		Desc:      "This is Product 12.",
		Price:     3.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 13,
		Name:      "Product 13",
		Desc:      "This is Product 13.",
		Price:     3.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 14,
		Name:      "Product 14",
		Desc:      "This is Product 14.",
		Price:     4.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 15,
		Name:      "Product 15",
		Desc:      "This is Product 15.",
		Price:     4.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 16,
		Name:      "Product 16",
		Desc:      "This is Product 16.",
		Price:     4.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 17,
		Name:      "Product 17",
		Desc:      "This is Product 17.",
		Price:     4.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 18,
		Name:      "Product 18",
		Desc:      "This is Product 18.",
		Price:     5.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 19,
		Name:      "Product 19",
		Desc:      "This is Product 19.",
		Price:     5.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 20,
		Name:      "Product 20",
		Desc:      "This is Product 20.",
		Price:     5.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 21,
		Name:      "Product 21",
		Desc:      "This is Product 21.",
		Price:     5.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 22,
		Name:      "Product 22",
		Desc:      "This is Product 22.",
		Price:     6.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 23,
		Name:      "Product 23",
		Desc:      "This is Product 23.",
		Price:     6.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 24,
		Name:      "Product 24",
		Desc:      "This is Product 24.",
		Price:     6.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 25,
		Name:      "Product 25",
		Desc:      "This is Product 25.",
		Price:     6.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 26,
		Name:      "Product 26",
		Desc:      "This is Product 26.",
		Price:     7.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 27,
		Name:      "Product 27",
		Desc:      "This is Product 27.",
		Price:     7.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 28,
		Name:      "Product 28",
		Desc:      "This is Product 28.",
		Price:     7.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
	{
		ProductID: 29,
		Name:      "Product 29",
		Desc:      "This is Product 29.",
		Price:     7.00,
		Inventory: 300,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 30,
		Name:      "Product 30",
		Desc:      "This is Product 30.",
		Price:     8.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 90,
		UnitSold:  200,
	},
	{
		ProductID: 31,
		Name:      "Product 31",
		Desc:      "This is Product 31.",
		Price:     8.00,
		Inventory: 200,
		Rating:    4,
		RatingNum: 90,
		UnitSold:  180,
	},
	{
		ProductID: 32,
		Name:      "Product 32",
		Desc:      "This is Product 32.",
		Price:     8.00,
		Inventory: 200,
		Rating:    3.5,
		RatingNum: 100,
		UnitSold:  180,
	},
}
